### PR TITLE
Change memory to mem

### PR DESCRIPTION
**Pull request by Big-Shark**

### CODE REVIEW

**Comment by robin850** [comment]
Hi @Big-Shark,

Thanks for the patch! Are you sure that `mem` is correct ? Looking at [Propel's source](https://github.com/propelorm/Propel2/blob/b9fe16f616fbef1e7c1a4943df08f3f1a04d7a41/src/Propel/Common/Config/PropelConfiguration.php#L256), it seems that `memory` is the good one.

**Comment by Big-Shark** [comment]
[Look!](https://github.com/propelorm/Propel2/blob/b9fe16f616fbef1e7c1a4943df08f3f1a04d7a41/src/Propel/Runtime/Util/Profiler.php#L192)  ))
And look [this](https://github.com/propelorm/Propel2/blob/b9fe16f616fbef1e7c1a4943df08f3f1a04d7a41/src/Propel/Runtime/Util/Profiler.php#L206), we use ```$config['name']```, but key 'name' does [not supported](https://github.com/propelorm/Propel2/blob/b9fe16f616fbef1e7c1a4943df08f3f1a04d7a41/src/Propel/Common/Config/PropelConfiguration.php#L251).
At the moment it does not work, I will try to do pull request today.

**Comment by Big-Shark** [comment]
propelorm/Propel2#983

**Comment by Big-Shark** [comment]
@robin850 @marcj merged my pr

**Comment by robin850** [comment]
Thanks!

**Pull request merged**
