### PR TITLE
"enum" als columntype was missing

### PR DESCRIPTION
**Pull request by IceShack**

### CODE REVIEW

**Comment by robin850** [comment]
Hi @IceShack,

Thanks for the pull request ; actually, the list seems [incomplete](https://github.com/propelorm/Propel2/blob/2951d2241fc69f3fb925ddc3d087cba0a04bed9a/resources/dtd/database.dtd#L87-L94), I don't know if we should list all available types or just the common ones and then link to the DTD.

@marcj : Should this list be exhaustive or not ?

**Comment by marcj** [comment]
I guess yes :)

**Comment by robin850** [comment]
@IceShack : Could you update your pull request to make the list of available types exhaustive please ? :-)

**Comment by IceShack** [comment]
@robin850, @marcj,
I added all missing types from PropelTypes class.

**Comment by robin850** [comment]
Thanks @IceShack and sorry for the delay ! :-)

**Pull request merged**
